[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 4321

[[contexts]]
  name = "local"
  build_command = "npm run build:local"
  publish = "dist"

[context.local.environment]
  NODE_ENV = "local"
